### ISSUE TITLE
Add SPS30 support

### ISSUE THREAD

**Issue by codyc1515** [arouanet/homebridge-sensirion#1]
Hi there

Is there any chance you may be able to add support for the SPS30?

Kind regards

**Comment by arouanet** [comment]
Hi Cody,

I might add support for the SPS30 in the future, but probably not right away. 

My initial goal for this plugin is to support the Sensirion SGP30 (VOC sensor) and the Sensirion SHT31 (temperature and humidity sensor) to monitor indoor air quality and emulate an Eve Room device. This is still in early stages of development, and I think I will focus on that for now.

In fact, I should probably rename the plugin to something like homebridge-sensirion-iaq (for Indoor Air Quality); homebridge-sensirion gives the impression that it will eventually support all Sensirion sensors, which might be too broad a scope for a single plugin.

Are you using the SPS30 for indoor or outdoor air quality monitoring?

**Comment by codyc1515** [comment]
I’m using it for indoors, but have also used it outdoors. I’ll see if I can make this work. Will be really nice to have everything just in NodeJS. Right now I have a bunch of dodgy Python scripts that, while working reliably, are annoying if I have to shift / re-install hardware.

**Comment by codyc1515** [comment]
Looks like this project is abandoned. Closing.
